set_property IOSTANDARD LVCMOS33 [get_ports {r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property PACKAGE_PIN N19 [get_ports {r[3]}]
set_property PACKAGE_PIN J19 [get_ports {r[2]}]
set_property PACKAGE_PIN H19 [get_ports {r[1]}]
set_property PACKAGE_PIN G19 [get_ports {r[0]}]
set_property PACKAGE_PIN D17 [get_ports {g[3]}]
set_property PACKAGE_PIN G17 [get_ports {g[2]}]
set_property PACKAGE_PIN H17 [get_ports {g[1]}]
set_property PACKAGE_PIN J17 [get_ports {g[0]}]
set_property PACKAGE_PIN J18 [get_ports {b[3]}]
set_property PACKAGE_PIN K18 [get_ports {b[2]}]
set_property PACKAGE_PIN L18 [get_ports {b[1]}]
set_property PACKAGE_PIN N18 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN U18 [get_ports clr]
set_property PACKAGE_PIN W5 [get_ports clk]							
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN T18 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property PACKAGE_PIN W19 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property PACKAGE_PIN T17 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property PACKAGE_PIN U17 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports clr]
set_property PACKAGE_PIN U18 [get_ports clr]


set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]